hash-format = "sha256"

[[files]]
file = "config/appliedenergistics2/client.json"
hash = "8e1abdf2a5ca581b487476ee413c4aaeb73b3173a2eb9512d41443cab9db5bbc"

[[files]]
file = "config/appliedenergistics2/common.json"
hash = "cfc234f9534de62f17c9fbfec3b0677087fe74d95ea437f4f1ad3be67057d776"

[[files]]
file = "config/quickconnectbutton.json5"
hash = "18748ba491e80d1a39de537aa734808e10e215eacc19fa29270c25bd19291e57"

[[files]]
file = "mods/addadd.pw.toml"
hash = "357b2fb5e67083512ec326cef82acccb642d2a93b81cb462f299e598b1d4ab0e"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
hash = "5f99a9e80c2ea75a4151e0d811fda950fff06ccb2e29a1724777069d6d9e84ed"
metafile = true

[[files]]
file = "mods/applied-energistics-2-wireless-terminals.pw.toml"
hash = "f14ca282df4cf9682f22b64ce59365caf11e7295d61746a16b9aa32de9da2eb6"
metafile = true

[[files]]
file = "mods/arch-ex.pw.toml"
hash = "93832714249249b2828a5cd357377e6e7d7a67d6f8aea7209fd83fccee935f9e"
metafile = true

[[files]]
file = "mods/architects-palette-fabric.pw.toml"
hash = "5d068ee053bfe3b7815d9b28b12144aaf65f9253247eff40480aacf3c2a8e02e"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "9ab81bd4f0c97596e3b9f5270d226f8fb41c91fd30b5637905b81e7dcb29c4d8"
metafile = true

[[files]]
file = "mods/artisanat.pw.toml"
hash = "5de92673edf1632d8be681c9beb7c218002a70d2094a2f1d86c75afc4d597cce"
metafile = true

[[files]]
file = "mods/aurorasdecorations-1.0.0+1.18.jar"
hash = "3093416206095bd0d5331012808e579c22144b0661ae9c46dcab9beadffd1acb"

[[files]]
file = "mods/bagels-baking.pw.toml"
hash = "d20e9001535b1abf2a52139c0c94ef314830b7141dd97a97681bd5ee589935b9"
metafile = true

[[files]]
file = "mods/bits-and-chisels.pw.toml"
hash = "1dea45a775887e68b1cafb587498dfa5514b3ea8d17ea58783920397f89ff7d7"
metafile = true

[[files]]
file = "mods/blur-fabric.pw.toml"
hash = "f781e21b5f5ac35b6b9be2a8219dcce459ad7564581c2f9a1c83059b48c82efc"
metafile = true

[[files]]
file = "mods/botania.pw.toml"
hash = "c2dc3701c79aad2fa278359d47c32d4e4a10c349b0fc06e8b7400dec9b48700c"
metafile = true

[[files]]
file = "mods/campanion.pw.toml"
hash = "8d3de765ffa83b0499e328dbd1827e35c2a9f88c11cdc09ba1f4efe7d68f531f"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "ba165681b7734d6b75adcb2880c1195d79210abccf2ed7d9f3f3175857e60185"
metafile = true

[[files]]
file = "mods/charm.pw.toml"
hash = "3d92bb395633472dac89164cdb9c1509182d27441e652d7fecd78bc9ed6efe4c"
metafile = true

[[files]]
file = "mods/chocolate-bar.pw.toml"
hash = "76a0fb83cd95b22bc9326bdd8efe648b76cb329c32440e7c68fd877ac8f7f1e8"
metafile = true

[[files]]
file = "mods/consistencyplus.pw.toml"
hash = "9f6e91210d4f90007541000ff482119f9b228d318e0d2eb0234cfcb38b53a81f"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "3476857955abc3053155ef32f1479594d3a7b61e522d570d66f1d0d327b4ecf8"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "f59359dcae8d9da125653d9127157a53ee780cff1580d9dcddfff8b9f0a167a9"
metafile = true

[[files]]
file = "mods/culinaire.pw.toml"
hash = "2729c49a56c9b94101d7baeb853945ae660cc1e6691abc6c402eef283901286c"
metafile = true

[[files]]
file = "mods/dawn.pw.toml"
hash = "b60fc5c154d6ca0e07406638d53bfbaa751e3ef517ff553fcec8543847844728"
metafile = true

[[files]]
file = "mods/displaycase.pw.toml"
hash = "a0375cf1693d99558e227044b903476f62897e7ac93b5339ba66ff5897f6d65d"
metafile = true

[[files]]
file = "mods/extended-drawers.pw.toml"
hash = "dfa7afb1d9f09e2eef314cd669d9ce61b9c97e5c69025dbaad34e9c2ee5a7fa4"
metafile = true

[[files]]
file = "mods/fabric-chisel.pw.toml"
hash = "7cc2807ba2777fa8303ee16393523a8767fa7f9c49fb71a094e62c1a439a25fd"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "c57ab7e92b672af93416304950b083d0b20aabe41af61d0993292dfef80744bf"
metafile = true

[[files]]
file = "mods/feature-nbt-deadlock-be-gone.pw.toml"
hash = "b1dd26068945a52c7989b2515cac0b51a14d25fedbf5c858e4c4d689fc38b2e5"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "f19e328fe42f91d1b65e244ee5bcf70f1e5305a27278945098ea85af82e05d0d"
metafile = true

[[files]]
file = "mods/haema.pw.toml"
hash = "429d7a134951d0b11b920b6eb0ad07d7bbe73b1a254d022719633a3f875fed9f"
metafile = true

[[files]]
file = "mods/hexcasting-fabric-1.18.2-0.9.0.jar"
hash = "fb60126f9724f806593e680da16131aeaf1b47e03a083974168f9aa7e5c38f41"

[[files]]
file = "mods/incorporeal-3.pw.toml"
hash = "b2b05a5a95aa2039b183177ab086f1d5e36506ca83be68c8b3d88270743a45fd"
metafile = true

[[files]]
file = "mods/inspecio.pw.toml"
hash = "7baba0d5b6448760f7a0ad285c82633842efeeda7714571daa477486a4899c50"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "158c40f09b2ed4fe14f5f2925751796fe11f6baee7e1ac7f35931ad831631a3d"
metafile = true

[[files]]
file = "mods/lovely_snails.pw.toml"
hash = "cea7e57f790cde53db4a76005bca2079df37fcb43df16961fbc6b2e116100b9c"
metafile = true

[[files]]
file = "mods/mo-structures.pw.toml"
hash = "2d28482058d2d26425ce201ff66684944cbf3bac2841cf4fbc9157fe51830fbe"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "37b69a71c010cb7e4d10a84a7c0e44373566ddb19aaaf4428ff2bb9ade0692e1"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "22ead426c002828d3d2f4da9caf5454fabae689bbf4291020919da7909095794"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "efc2a5c84648fe9d84aaaae5ecdd352f3fff2a81857e53806f6a67d6e67dd845"
metafile = true

[[files]]
file = "mods/paucal-fabric-1.18.2-0.4.7.jar"
hash = "8042f40ab172af377453151e60283e9bd5da6c1564f960eadb751dedfda523b0"

[[files]]
file = "mods/qsl.pw.toml"
hash = "2056e66a16b6e3bbef4e56eaeddc744e92acee372ebd8a3c7c90750170e61665"
metafile = true

[[files]]
file = "mods/quickconnectbutton.pw.toml"
hash = "14056e199239c88e18eb249e0133fd0788fd0e5e86eb12e2d4ea519b25ce10d4"
metafile = true

[[files]]
file = "mods/quilt-loading-screen.pw.toml"
hash = "8c0b6b4af1aa2dda3b4d09ac32640b4f06523100a66be0c794d39688bacae3bc"
metafile = true

[[files]]
file = "mods/repurposed-structures-fabric.pw.toml"
hash = "6b51b49e8ca818449735833e918d6e5edf1905d46347571f569b3c2c00d21d06"
metafile = true

[[files]]
file = "mods/roughly-enough-items.pw.toml"
hash = "9e07fe34dd1986b1873d4e32a224307124f08c280d1db5d2e44320e98b17049d"
metafile = true

[[files]]
file = "mods/sandwichable.pw.toml"
hash = "da403a55fd88f2d2aeacec6de320b7c8fb5010a7de8b831414fb4933681c9f44"
metafile = true

[[files]]
file = "mods/simplevillagers.pw.toml"
hash = "e08c15ad879b230dcd156d2674fdd179c613a41a95c6495c7118212de4a69a55"
metafile = true

[[files]]
file = "mods/tatercart.pw.toml"
hash = "ab8a92709aead924bceb04b0994c23d99f546a94c64cc33bdf2c188f8235f646"
metafile = true

[[files]]
file = "mods/teenycoal.pw.toml"
hash = "fe0e1465338719573a2d07fe26cc4833a707d3a96f10578e095dd60aeacaca02"
metafile = true

[[files]]
file = "mods/this-rocks.pw.toml"
hash = "ba4c85d3c6da8cd0ea27bae046c59a39009b1c703af0a9ace73cf9a4164b2dfe"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "49f5590e6160266691eaca6948b33a3a2763e590ed4bcf90189f13650066c84e"
metafile = true

[[files]]
file = "mods/twigs.pw.toml"
hash = "44f75bcda587cd98b95f19dc02abdc69a6153310afd5c06a3cc75bf1b3b9ca06"
metafile = true

[[files]]
file = "options.txt"
hash = "5550969b4452732ae5e1603b262177de776f65327fda1db9ac62629222e7ee7f"
