name = "Pumpkin Lands"
author = "mounderfod"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fac110ad0213bb5448ae4463c8c21bad151a4ba9c4dd782e0833a96016389f08"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.2"
