name = "Pumpkin Lands"
author = "mounderfod"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a34c88fa610900c2196d286901a34ed60212e8a22ae17d988267d4ecc4f625b"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.2"
